"""Add Review Model

Revision ID: a7d1c8de1b70
Revises: fef76c3f3aa7
Create Date: 2025-03-10 19:42:54.499134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d1c8de1b70'
down_revision = 'fef76c3f3aa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
